version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: mlflow_db
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    image: mlflow/mlflow
    container_name: mlflow
    depends_on:
      - postgres
    environment:
      BACKEND_STORE_URI: postgresql://mlflow_user:yourpassword@postgres:5432/mlflow_db
      ARTIFACT_ROOT: /mlruns
    command: mlflow server --backend-store-uri=$${BACKEND_STORE_URI} --default-artifact-root=$${ARTIFACT_ROOT} --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns

  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: rul-app
    depends_on:
      - postgres
      - mlflow
    env_file:
      - ../.env
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "8000:8000"
    volumes:
      - ../mlruns:/app/mlruns

volumes:
  pgdata:
