version: "3.9"

services:
  rul-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: rul-inference-api
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
